### ISSUE TITLE
Build Frontend for Purchase Orders Page

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#100]
**Task Tests**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "user1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Purchase Orders" in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/purchase_orders.php
6) Verify if you can see existing orders
7) Go to https://github.com/cse442-at-ub/project_s23-one-belt-one-road/blob/main/purchase_orders.php
8) Verify if the line require_once 'apiFunctions.php'; is in the code for using API

**Comment by anht-11** [comment]
another task test step to verify only the logged in user has the access to the page?
