### ISSUE TITLE
Create Listed Items button on my account page

### ISSUE THREAD

**Issue by JiajunGao88** [cse442-at-ub/project_s23-one-belt-one-road#104]
**Task Tests**

*Test 1:*

1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "asddsa" and the password "asddsaasd", then click on "Log In".
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Listed Items" button in the center of the page.
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/my-listed-items.php

**Comment by anht-11** [comment]
Should a task block another task?
