### ISSUE TITLE
As a student seller, I want to post items for sale so that I can get paid for them

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#108]
Acceptance Tests:

Test 1:
1) Go to the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “test17”
3) Click on the password text box and input “password”
4) Click on the "Sign in" button on the bottom of the page
5) Be redirected to the account page, in the top right corner click on the button that sats "Sell"
6) Click the "Post" button at the bottom of the page
7) Remain on the page and see a message stating "Please fill out this field" from the item name textbox

Test 2:
1) Go to the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “test17”
3) Click on the password text box and input “password”
4) Click on the "Sign in" button on the bottom of the page
5) Be redirected to the account page, in the top right corner click on the button that sats "Sell"
6) Enter "Black Nike Backpack" into the "Item Name" field
7) Enter -100 into the "Price (Per Unit):" field
8) Click the "Post" button at the bottom of the page
9) Remain on the page and see a message stating "Value must be greater than or equal to 0.01" from the "Price" textbox

Test 3:
1) Go to the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “test17”
3) Click on the password text box and input “password”
4) Click on the "Sign in" button on the bottom of the page
5) Be redirected to the account page, in the top right corner click on the button that sats "Sell"
6) Enter "Black Nike Backpack" into the "Item Name" field
7) Enter 30 into the "Price (Per Unit):" field
8) Enter "new" into the "Description" field
9) Click the "Post" button at the bottom of the page
10) Remain on the page and see a message stating "Please lengthen this input to 10 characters or more ...." from the "Description" textbox

Test 4:
1) Go to the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “test17”
3) Click on the password text box and input “password”
4) Click on the "Sign in" button on the bottom of the page
5) Be redirected to the account page, in the top right corner click on the button that sats "Sell"
6) Enter "Black Nike Backpack" into the "Item Name" field
7) Enter 30 into the "Price (Per Unit):" field
8) Enter "Black Nike backpack, used but looks new! " into the "Description" field
9) Enter 1 into the "Item Quantity" field
10) Click on the box to add an image on the left side of the screen, and upload a jpg file
11) Click the "Post" button at the bottom of the page
12) Be redirected to the my listed items page (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/my-listed-items.php)
13) See the item "Black Nike Backpack" under the "My Listed Items" tab

Test 5:
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/post_item.php (Do not log in)
2) Enter "Black Nike Backpack" into the "Item Name" field
3) Enter 30 into the "Price (Per Unit):" field
4) Enter "Black Nike backpack, used but looks new! " into the "Description" field
5) Enter 1 into the "Item Quantity" field
6) Click on the box to add an image on the left side of the screen, and upload a jpg file
7) Click the "Post" button at the bottom of the page
8) Remain on the same page and see an error message stating "Error: You must log in" in red in the middle of the screen

Test 6:
1) Go to the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “test17”
3) Click on the password text box and input “password”
4) Click on the "Sign in" button on the bottom of the page
5) Be redirected to the account page, in the top right corner click on the button that sats "Sell"
6) Enter "Black Nike Backpack" into the "Item Name" field
7) Enter 30 into the "Price (Per Unit):" field
8) Enter "Black Nike backpack, used but looks new! " into the "Description" field
9) Enter 1 into the "Item Quantity" field
11) Click the "Post" button at the bottom of the page
12) Remain on the same page and see a red message in the middle of the screen stating "Error: You must upload an image"

**Comment by anht-11** [comment]
add security protection
