### ISSUE TITLE
Implement post item for sale page

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#109]
Task Tests:

Test 1:
1) Verify the file post_item exists in the post-item-Chris branch exists on github
2) Verify there is an item name and item description input textbox
3) Verify there is a place to upload an image
4) Verify there is a place to input item quantity, and item price
5) Verify there is a button to post the item

**Comment by ghost** [comment]
Currently unable to work on rest of page because of an issue with permissions to allow users to upload files (the item image). We are supposed to have an uploads folder but I think it was deleted. I am waiting for cse-consult to fix the issue

**Comment by anht-11** [comment]
what is the user story this task blocking?
