### ISSUE TITLE
Build Frontend for Sale Orders Page

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#110]
**Task Tests**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "user1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Sale Orders" in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/sale_orders.php
6) Verify if you can see existing orders
7) Go to https://github.com/cse442-at-ub/project_s23-one-belt-one-road/blob/main/sale_orders.php
8) Verify if the line require_once 'apiFunctions.php'; is in the code for using API

**Comment by anht-11** [comment]
Can we make the test be more technical? These test cases seems to be more of acceptance tests, more than task tests

**Comment by anht-11** [comment]
maybe add another task test to make sure only logged in user have the access to the page?
