### ISSUE TITLE
As a student seller, I want to access to all my listed items so that I know the posted products and their status of stocks.

### ISSUE THREAD

**Issue by JiajunGao88** [cse442-at-ub/project_s23-one-belt-one-road#111]
**Acceptance Tests**

*Test 1:*

1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "user1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Listed Items" button in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/my-listed-items.php
6) Verify if you can see all listed items with their remaining amount of stocks

*Test 2:*

1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "empty1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Listed Items" button in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/my-listed-items.php
6) Verify if you can see “No listed item. Start listing your item now!” at the center of the page if there is no listed item.

*Test 3:*

1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "asddsa" and the password "asddsaasd", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Listed Items" button in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/my-listed-items.php
6) Verify if you can see all listed items with their remaining amount of stocks.
7) Verify if you can see one of the item has “Inventory: 0” at the end the specified item that out of stock.

**Comment by anht-11** [comment]
If there is no listed item, what the user is expected to see?
If there is an listed item that is out of stock, what is the user expected to see?

**Comment by anht-11** [comment]
make sure only the logged in user able to access the page

**Comment by anht-11** [comment]
remove the parenthesis part near the task test number
