### ISSUE TITLE
Create a procedure for creating products by sellers

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#121]
Task Tests

Test 1

1) Login into database using Ubit name and person number as credentials: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=1&db=cse442_2023_spring_team_j_db
2) Select "Procedure" from the left side
3) Verify that there exists a procedure called "addProduct"
4) Execute this procedure with input: ownerID=1, image="image path", inventory = 1000, description = {"color": "yellow"}, productName="cap", unit_price=10.0
5)Verify that there is a record added to product table with column values above

**Comment by anht-11** [comment]
what is the user story this task blocking?
