### ISSUE TITLE
Create a Post Page for Selling Items

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#14]
**Task Test**

*Test 1*

1) Go to https://www.figma.com/file/qXW0S7J0YT48satDEr5l5B/Pages?t=QvqB0g5NxTZZnOpH-6
2) Click the "SELL" button in the landing page
3) Verify if there is a post page
4) Verify if there are boxes to enter the item name and upload the item image
5) Verify if there are options to choose the item condition and the item category
6) Verify if there is a text box to enter the item description

**Comment by anht-11** [comment]
What if the item is found through search bar? What should other tests be covered?
