### ISSUE TITLE
Create an Product Detail Page in Figma

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#15]
**Task Test**

*Test 1*
1) Go to https://www.figma.com/file/qXW0S7J0YT48satDEr5l5B/Pages?t=QvqB0g5NxTZZnOpH-6
2) Verify if there is an item information page
3) Verify if the item information includes an item name, an image, and a price.
3) Verify if there is a seller information area that includes a seller name and a seller rating
4) Verify if there is a cart button for adding the item to the shopping cart.

**Comment by anht-11** [comment]
What should the item information page look like? Be detailed as possible.
