### ISSUE TITLE
As a customer user, I want to remove an item from my shopping cart so that I could keep only those I would like to buy.

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#16]
**Acceptance Tests**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php, enter "user1" as the username and "12345678" as the password, then click on "Log In" button
2) Click on the button which shows a shopping cart icon in the top-right corner
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/cart.php, and if there is at least one item on the page
4) Select one item and click on the "REMOVE" button which is at the right corner of the product block, then verify if only the selected block has disappeared.
5) If there is no product left, verify if there is "Your cart is empty." on the page.
6) Refresh the page, then verify the selected item has been removed permanently

*Test 2:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php, enter "empty1" as the username and "12345678" as the password, then click on "Log In" button
2) Click on the button which shows a shopping cart icon in the top-right corner
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/cart.php, and if there is no item on the page
4) Verify if there is "Your cart is empty." on the page.

**Comment by anht-11** [comment]
What if the item is added to the cart when the user is viewing the product, and they decide to remove the item when they are still on the same page?

**Comment by fhuang566** [comment]
> What if the item is added to the cart when the user is viewing the product, and they decide to remove the item when they are still on the same page?

The user would have to go into the shopping cart to remove the product once the "Adding to cart" action has already been performed. The shopping cart page would be the only place where users have access to manage items in their cart.

**Comment by fhuang566** [comment]
We have not started coding for front end yet, so we will carry this task into next sprint.

**Comment by anht-11** [comment]
Now that we have prepared query to remove items to shopping cart, how would you plan use this API to implement the interactive remove button? Please leave the comments in the issue regarding your plan on carrying this issue to next sprint

**Comment by harptin** [comment]
For Sprint 4:

When the user clicks on the remove button that we've added to the shopping cart UI, we'll trigger a request to the API endpoint that we've prepared for removing items from the shopping cart. This request will include the item ID that the user wants to remove.

Once the API receives the request, it will remove the item from the shopping cart in the backend.

After the API successfully removes the item, we'll update the shopping cart UI to reflect the changes, such as removing the item from the list of items and updating the total price.

Finally, we'll add some error handling to the UI to display an error message if the remove request fails for some reason, such as if the item ID is invalid.

**Comment by anht-11** [comment]
what does the shopping cart look like when there is no item to be removed?

**Comment by harptin** [comment]
Add a separate test for testing an empty cart using another account whose shopping cart without product

**Comment by anht-11** [comment]
I would suggest remove the parenthesis part near the test number, as this part does not follow the Style Guide format
