### ISSUE TITLE
Create a "Remove" button for each item in the shopping cart

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#17]
**Task tests**

*Test 1*
1) Open the landing page for One Belt One Road team project
2) Click on "View Shopping Cart" button of a shopping cart shape on the up-right corner
3) In the shopping cart page, verify that there is a button represented as "X" in the up-right corner of each added item block
4) In the HTML code, make certain the button has an id of "rmvFromCart"

**Comment by fhuang566** [comment]
We have not started coding for front end yet, so we will carry this task into next sprint.

**Comment by anht-11** [comment]
"A task should be completed in the sprint in which it is started. If a task is added to the Planned pipeline in one sprint, but does not get developed in that time, DO remove the original sprint label and replace it with the label from the new sprint." - Style Guide
