### ISSUE TITLE
Create an Order Confirmation Page.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#22]
**Task tests**

*Test 1*
1. Open the 'confirm.php' file in VS Code which will open a web page about the confirmation page.
2. Verify if there is order confirm message and order number.
3. Verify if there is Shipping Address, Payment Information and Order Summary.
4. In the HTML file, make certain that there is a page title named "Confirmation Page".

**Comment by anht-11** [comment]
"If a task is added to the Planned pipeline in one sprint, but does not get developed in that time, DO remove the original sprint label and replace it with the label from the new sprint." - Style Guide

A task blocks another user story and should not be blocked by any issue (tasks or user story)

**Comment by anht-11** [comment]
For task 2, you don't have to include figma here. A task should be for developer to test if all functionality work

**Comment by anht-11** [comment]
I believe there are other fields user need to input, so should we add these fields below the task tests?

**Comment by yigiaom** [comment]
Could you explain it? Because the confirm page currently only shows some text of confirmation message and payment information. I don't understand what the input fields represent to.

**Comment by anht-11** [comment]
I see, my bad. I have removed the revise tag.

**Comment by anht-11** [comment]
should this task block a user story? likely #9?
