### ISSUE TITLE
Create the Landing Page Front-End

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#28]
**Task Tests:**

*Test 1*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php and open the dev tools in the browser for inspecting elements
2) Verify if there is the header with a shopping cart image having the "href" attribute to the "cart.php", and a search-bar class having the "href" attribute to the search result PHP page with corresponding keywords
3) Verify if there is a "ul" listing trending items each with "li" containing an image and its name
4) Verify if each image has the "href" attribute to the "product_detail_page.php"

**Comment by anht-11** [comment]
The page will be hosted on the server, so make sure update the step 1 to have the url link to the server
