### ISSUE TITLE
As a buyer / seller, I want to register an account with a username and password so that I can buy and sell items

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#35]
**Acceptance Tests**

Test 1:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “1abcde”
3) Click on email text box and input "test@test.com"
4) Click on a password text box and input “password”
5) Click on a password verification text box and input “password”
6) Click on a "Sign up" button on the bottom of the page
7) Be redirected to "login" page

Test 2:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “2abcde”
3) Click on email text box and input "test@test.com"
4) Click on a password text box and input “1234”
5) Click on a password verification text box and input “1234”
6) Click on a "Sign up" button on the bottom of the page
7) Be redirected to the “Registration” page and see a message stating "Password must be at least 8 characters long."

Test 3:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “2abcde”
3) Click on email text box and input "test@test.com"
4) Click on a password text box and input “password”
5) Click on a password verification text box and input “password2”
6) Click on a "Sign up" button on the bottom of the page
7) Be redirected to the “Registration” page and see a message stating "Passwords do not match."

Test 4:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “userTest”
3) Click on email text box and input "test@test.com"
4) Click on a password text box and input “1234”
5) Click on a password verification text box and input “1234”
6) Click on a "Sign up" button on the bottom of the page
7) Be redirected to the “Registration” page and see a message stating my username is already in 
use

Test 5:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “ 1abcde !”
3) Click on email text box and input "test@test.com"
4) Click on a password text box and input “password”
5) Click on a password verification text box and input “password”
6) Click on a "Sign up" button on the bottom of the page
7) Be redirected to the “Registration” page and see a message stating "Username must contain only alphanumeric characters

Test 6:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on a "Sign up" button on the bottom of the page
3) Remain on “Registration” page and see a message stating "Please fill out this field." from the username textbox

Test 7:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “1abcde”
3) Click on email text box and input "test@test.com"
4) Click on a "Sign up" button on the bottom of the page
5) Remain on “Registration” page and see a message stating "Please fill out this field." from the password textbox

Test 8:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “1abcde”
3) Click on a "Sign up" button on the bottom of the page
4) Remain on “Registration” page and see a message stating "Please fill out this field." from the email textbox

Test 9:
1) Open the registration page at https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/Register.php
2) Click on username text box and input “1abcde”
3)Click on email text box and input "email"
4) Click on a "Sign up" button on the bottom of the page
5) Remain on “Registration” page and see a message stating "Please include an '@' in the email" from the email textbox

**Comment by ghost** [comment]
Test 1 assumes that the username is not already in use.

Test 4 assumes that the username is already in use.

**Comment by anht-11** [comment]
Include the link to the register page hosted on the server
