### ISSUE TITLE
As a registered user, I want to log in with my username and password, so that I can access my account

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#37]
**Acceptance Tests**

Test 1:
1) Open login page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “user”
3) Click on a password text box and input “hash4321”
4) Click on a "Sign in" button on the bottom of the page
5) Be redirected to the landing page

Test 2:
1) Open the login page here: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “1abcde”
3) Click on a password text box and input “1234567”
4) Click on a "Sign in" button on the bottom of the page
5) Be redirected to the “Login" page and see message at top of page stating 'Invalid username or password. Please try again.'

Test 3:
1) Open the login page here:  https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Click on username text box and input “2abcde”
3) Click on a password text box and input “1234”
4) Click on a "Sign in" button on the bottom of the page
5) Be redirected to the “Login" page and see message at top of page stating 'Invalid username or password. Please try again.'

**Comment by ghost** [comment]
Test 1 is assuming username and password combination is a valid user in database

Test 2 is assuming username exists as a valid account in database, but the password is incorrect

Test 3 is assuming username does not exist in user database

**Comment by anht-11** [comment]
You might consider changing the title, especially the observable outcome, as the team finalizes redirecting to the landing page after logging in. Think about what is the action of the user do here to trigger the function login. Think about what is the observable outcome when user is logged in.

Test 2 , Test 3 - specify the error message and put it in quotes.

**Comment by anht-11** [comment]
include the link to the login page hosted on the server
