### ISSUE TITLE
Create a Product Detail Page Front-End

### ISSUE THREAD

**Issue by JiajunGao88** [cse442-at-ub/project_s23-one-belt-one-road#42]
**Task Tests:**

*Test 1*

1. Pull the Product Detail Page Branch in Github to local.
2. Verify if there is a product_detail_page file for the specific item and run it.
3. Verify if there is a header with a logo, a shopping cart button, and a search bar.
4. Verify if the item has its name, condition, seller, seller rating, price, and description.
5. Verify if there is an "Add to Cart" button and after clicking on it if added to the cart successfully.

**Comment by anht-11** [comment]
Double check the label for this task and the format of writing task tests in Style Guide
