### ISSUE TITLE
Create store procedures for accessing user infomation from database

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#45]
**Task Tests**

*Test 1*
1) Go to database management tool and open the database with the link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_routines.php?server=1&db=cse442_2023_spring_team_j_db&type=PROCEDURE
2) Open "Procedures" tab
3) Make certain that there is a procedure called "getAllUsers"
4) Execute the procedure
5) Verify that the procedure returned all the user recod with "username", "password", and "email" 

*Test 2*
1) Go to database management tool and open the database with the link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_routines.php?server=1&db=cse442_2023_spring_team_j_db&type=PROCEDURE
2) Open "Procedures" tab
3) Make certain that there is a procedure called "getUserByID"
4) Execute the procedure with parameter an "userID", for example: 1 
5) Verify that the procedure returned correct user infomation which contains the username, password, and email, corresponding to specified userID

**Comment by anht-11** [comment]
What is the user story that is currently blocked by this task? Are we missing any tags here - sprint tag and task tag?
Should the issue jump directly from Backlog to Completed?
