### ISSUE TITLE
As a customer user, I want to add an item to my shopping cart in product detail page so that we could pay multiple items at the same time in shopping cart.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#5]
**Acceptance Tests**

*Test 1*
1) Open the https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/, login with credentials (username: user1, passward: 12345678), once you logged in, click the "ubay" logo to navigate to landing page.
2) In the landing page, select the first product in the "Trending" area to check if it leads to the product detail page.
3) On the product detail page, click on "Add to Shopping Cart" with the default value of size and quantity.
4) After clicking the button, check if there is a message popup in the middle of the screen that says "Added to cart successfully".
5) Find "View Shopping Cart" button of a shopping cart shape on the up-right corner of the product detail page and click on it
6) After switching to the shopping cart page, check if the selected item has been successfully added to the shopping cart.

*Test 2*
1) Open the https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/, login with credentials (username: user1, passward: 12345678), once you logged in, click the "ubay" logo to navigate to landing page.
2) In the landing page, use the search bar to search for a specific product by entering its name or keyword, and press enter.
3) From the search results, select a product to navigate to its product detail page.
4) Click on the "Add to Shopping Cart" button.
5) Verify if a message popup appears in the middle of the screen, stating "Added to cart successfully".
6) Click on the "View Shopping Cart" button, represented by a shopping cart icon, located in the upper-right corner of the product detail page.
7) Once redirected to the shopping cart page, confirm if the selected item with the specified size and quantity has been successfully added to the shopping cart.

*Test 3*
1) Open the https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/, login with credentials (username: user1, passward: 12345678), once you logged in, click the "ubay" logo to navigate to landing page.
2) In the landing page, use the search bar to search "Hoodie".
3) Select the specified item that displayed to access its product detail page which has inventory column states “Out of Stock”.
4) Verify there should be an unclickable button "Out of Stock".

**Comment by fhuang566** [comment]
This user story has been blocked by a few unfinished tasks. We will continue to work on tasks related to this user story in next sprint.

**Comment by anht-11** [comment]
what are differences in these test cases?

**Comment by JiajunGao88** [comment]
Fixed and updated.

**Comment by anht-11** [comment]
@grayedge Now that we have prepared query to add items to shopping cart, how would we use this API to implement the interactive add button? Please leave the comment in the issue regarding how you plan to carry this issue to next sprint

**Comment by harptin** [comment]
For Sprint 4:

Before triggering the request to add the item to the shopping cart, we'll first verify if the user is logged in. If the user is not logged in, we'll show an alert message to prompt the user to log in and then take them to the login page.

When the user clicks on the "Add to Cart" button on the product detail page after logging in, we'll trigger a request to the API endpoint that we've prepared for adding items to the shopping cart. This request will include the product ID and the quantity of the item that the user wants to add.

Once the API receives the request, it will add the item to the shopping cart in the backend.

After the API successfully adds the item, we'll update the shopping cart UI to reflect the changes, such as adding the item to the list of items and updating the total price.

We'll also add some error handling to the UI to display an error message if the add-to-cart request fails for some reason, such as if the product ID is invalid or the quantity is not available in stock.

If the user adds multiple items to the shopping cart, we'll ensure that the quantity of each item is correctly reflected in the shopping cart UI and that the total price is updated accordingly.

**Comment by anht-11** [comment]
What is the link to the e-commerce website? What is the process of logging in? What is the link to the shopping cart page?

**Comment by anht-11** [comment]
Test 3, step 2, do we agree having the feature of category implemented? If not, should we include it here?

**Comment by anht-11** [comment]
what the user is expected to see, if there is an item that is out of stock?

**Comment by anht-11** [comment]
what is the user expected to see, if there is an item listed yet out of stock? Are they able to add that item to the shopping cart?

**Comment by anht-11** [comment]
update the url - e-commerce website and product detail page

**Comment by anht-11** [comment]
update error message that instruct user what to do next, instead of simply stating the error
