### ISSUE TITLE
As a frequent online shopper, I want to be able to search for products using keywords in the search bar so that I can quickly find the specific items I am looking for.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#51]
**Acceptance Test:**

*Test 1*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input keyword "mug" in the search bar on the landing page and click on Search button.
3. Verify if you are redirected to item listing page which shows a bunch of items relevant to the keyword.

*Test 2*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input nothing in the search bar on the landing page and click on Search button directly.
3. Verify if you are redirected to item listing page which shows all items that's on sale.

*Test 3*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input "airplane" in the search bar on the landing page and click on Search button.
3. Verify if you are redirected to item listing page which shows nothing.

*Test 4*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input a misspelled keyword, such as "mag" instead of "mug", in the search bar on the landing page and click on Search button.
3. Verify if you are redirected to item listing page which shows nothing.

*Test 5*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input \ (backslash) in the search bar on the landing page and click on Search button.
3. Verify an ERROR message shows that "Invalid input".

**Comment by anht-11** [comment]
Can only implementing an item listing page complete this user story? Should the user story be broken down into multiple tasks?

**Comment by anht-11** [comment]
new test cases for when user input invalid info (sql injection attack)?

**Comment by anht-11** [comment]
@chrisStuhler how about creating api for queries of searching the a product through search bar?

**Comment by anht-11** [comment]
@yigiaom has the feature of searching an item through search bar been tested on the server? If yes, should this user story be moved to COMPLETED pipeline?
