### ISSUE TITLE
Create queries for retrieving items data displayed in the shopping cart

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#54]
**Task tests**

**Test 1**

1) Go to database management page; link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=1&db=cse442_2023_spring_team_j_db
2) Open "Procedures" tab
3) Verify that there exists a procedure called "getShoppingCartByUserID"
4) Execute the procedure with specified parameter which is a user's ID
5) Make certain that the returned value contains all the products which were added to the correspnding user's shopping cart

**Comment by anht-11** [comment]
@fhuang566 What is the user story this task linked to?
