### ISSUE TITLE
As a user perfer getting data conveniently, I want to click on a "My Account" button so that I can see my account information

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#59]
**Accepentance Test**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter "user1" for the username and "12345678" for the password, then click on the log in button
3) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php
4) Click the "My Account" button at the top right of the page
5) Verify if it is directed to the https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
6) Verify if it shows your information, including the username and the email
7) Verify if it shows two buttons for purchase orders and sale orders

*Test 2:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php, without follow the step of logging in (test 1)
2) Verify if it shows "oops, no username returned" and "oops, no email returned"

**Comment by anht-11** [comment]
Can only implementing the account page front end is enough for completing this user story? Should this user story broken down into any tasks?

**Comment by anht-11** [comment]
Can we specify the action generating the account page? What button needs clicking on to view the account page?

EDIT: as the account page has yet to show the orders made by the user, how about revising the title to reflect the current feature?

**Comment by anht-11** [comment]
Add more test cases when the user is attempted to go to my account page, when they have not been successfully logged in yet
