### ISSUE TITLE
Create an API with documentation to remove items from a user's shopping cart

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#60]
Task Tests

Test 1:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called apiFunctions
2) Verify there is a function named 'removeFromShoppingCart', which invokes the 'removeFromShoppingcart' database procedure
4) Verify the function function has input parameters named UserID, ProductID, and Amount.

Test 2:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called apiFunctions
2) Verify there are instructions on how to use the API
3) Verify there is documentation indicate the succusses of an API call to the developer

Test 4:
1) Go to database management page; link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=1&db=cse442_2023_spring_team_j_db
2) Open "Procedures" tab
3) Execute the procedure 'removeFromShoppingCart' with parameters:  userID=1, ProductID=1, and Amount=2.
4) Invoke removeFromShoppingCart API with parameters userID=1, ProductID=1, and Amount=2. Verify the API call and database procedure have the same result in the database.

**Comment by anht-11** [comment]
A task should block one user story. In this case, How are these APIs can be used to complete a specific user story? Hint: the user story with remove item from shopping cart and the user story with add items to shopping cart
