### ISSUE TITLE
Create an API with documentation to connect to the database

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#61]
Task tests

Test 1:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called apiFunctions
2) Verify there are function named 'establish_connection', that takes no parameters
3) Verify the function returns a 'conn' variable
4) Verify there is a function named 'close_connection', that takes a 'conn' as a parameter

Test 2:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called apiFunctions
2) Verify there are explanations of each parameters listed above for 'establish_connection', and how to use the API.
3) Verify the documentation clearly states you must call 'close_connection' after invoking 'esatblish_connection'

Test 3:
1) Invoke the establish_connection function by calling it with establish_connection();
2) Set a variable named conn to the above function call (ie conn = establish_connection())
3) Verify if (!$conn) returns false

Test 4:
1) Invoke the establish_connection function by calling it with establish_connection();
2) Set a variable named conn to the above function call (ie conn = establish_connection())
3) Verify if (!$conn) returns false
4) Invoke 'close_connection' with conn as the parameter
5) Verify if (!$conn) returns true

**Comment by anht-11** [comment]
How about grouping all functions (API endpoint) to one file, instead having separate files for different function? The same advices goes for #60, #61, #62
