### ISSUE TITLE
Create an API with documentation to retrieve items listed for sale

### ISSUE THREAD

**Issue by ghost** [cse442-at-ub/project_s23-one-belt-one-road#62]
Task Tests

Test 1:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called apiFunctions
2) Verify there is a function named 'getAllItems', which invokes the 'getAllProduct' database procedure
3) Verify there is a function named 'getNItems', which invokes the 'getLandingPageProduct' database procedure.
4) Verify getNItems takes an integer named 'productCount' as a parameter and returns a list of items

Test 2:
1) Go to our project GitHub at https://github.com/cse442-at-ub/project_s23-one-belt-one-road and verify there is a file called  apiFunctions
2) Verify there are instructions for 'getAllItems' and 'getNItems', and explanations of the return values

Test 3:
1) Go to database management page; link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=1&db=cse442_2023_spring_team_j_db
2) Open "Procedures" tab
3) Execute the procedure "getAllProduct"
4) Invoke getAllItems API. Verify results match getAllProduct results

Test 4:
1) Go to database management page; link: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=1&db=cse442_2023_spring_team_j_db
2) Open "Procedures" tab
3) Execute the procedure "getLandingPageProduct" with parameter "productNumber=4"
4) Invoke getNItems API with parameter productCount = 4. Verify results match getLandingPageProduct results

**Comment by anht-11** [comment]
What is the difference between #62 and #61? I think this misunderstanding can be resolved if we can have this task block a specific user story?

**Comment by anht-11** [comment]
Missing tag? task tag?
