### ISSUE TITLE
Create template file for product detail page

### ISSUE THREAD

**Issue by JiajunGao88** [cse442-at-ub/project_s23-one-belt-one-road#63]
**Task Tests**

*Test 1*
1. Create a new PHP file in your project's templates directory called "product.php".
2. Open the "product.php" file and include any necessary PHP files (such as your database connection file) at the top of the page.
3. Define a variable called "$productId" and set it equal to the ID of the product you want to display. This ID can be passed in via a query string parameter or retrieved from a database query.
4. Write a database query to retrieve all of the necessary information about the product with the given ID. This may include the product name, description, price, image URL, etc.
5. Use PHP to output the product information within the HTML markup of your template. For example, you might use the following code to output the product name:
`<h1><?php echo $product['name']; ?></h1>`
6. Save the "product.php" file and navigate to a product detail page on your e-commerce website. You should see the product information displayed using the template you just created.

**Comment by anht-11** [comment]
This task is related to the product detail page, so you might consider linking to the related user story - hint: the one with viewing one specific product detail

**Comment by anht-11** [comment]
what is a user story this task is blocking?
