### ISSUE TITLE
Modifying the header file to prevent security attack.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#65]
**Task Tests**

*Test 1*
1. Open the link of our project: https://github.com/cse442-at-ub/project_s23-one-belt-one-road/tree/dev.
2. In the header.php file, verify if 'filter_var' function used to prevent XSS attacks and SQL injection attacks

**Comment by anht-11** [comment]
which file should we look at to find this function?
