### ISSUE TITLE
As a student seller, I want to click an item image so that I can see the detail information of the item

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#7]
**Acceptance Test:**

*Test 1*
1) Go to the landing page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php
2) Verify if there are 4 image blocks
3) Click on the first image
4) Since it is not possible to know which specific item would be fetched by the API, just verify if it is redirecting to the item page, and its URL starts with https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/product_detail.php?productID= and ends with a number, which is the product ID.

*Test 2*
1) Go to the landing page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php
2) Verify if there are 4 image blocks
3) Click on the second image
4) Since it is not possible to know which specific item would be fetched by the API, just verify if it is redirecting to the item page, and its URL starts with https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/product_detail.php?productID= and ends with a number, which is the product ID.

*Test 3*
1) Go to the landing page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php
2) Verify if there are 4 image blocks
3) Click on the third image
4) Since it is not possible to know which specific item would be fetched by the API, just verify if it is redirecting to the item page, and its URL starts with https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/product_detail.php?productID= and ends with a number, which is the product ID.

*Test 4*
1) Go to the landing page: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/index.php
2) Verify if there are 4 image blocks
3) Click on the fourth image
4) Since it is not possible to know which specific item would be fetched by the API, just verify if it is redirecting to the item page, and its URL starts with https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/product_detail.php?productID= and ends with a number, which is the product ID.

**Comment by anht-11** [comment]
As a user, what is a login should be? What should they expect to do to login successfully?

What if the user does not click on the item image that is on the landing page; instead, they search the item first, then click on the image later, what should they see? 

Missing the sprint label.

**Comment by anht-11** [comment]
Please be more specific in "login with an existing user account" - what is the username and password for tester to login? Test 2, step 3, some keywords seem vague, can the test be more specify in term of what keywords tester should provide?

**Comment by anht-11** [comment]
I suggest we move this issue back to in-progress and label sprint 2, as this user story is incomplete at the end of the sprint 1.

**Comment by harptin** [comment]
For Test 2, we would test it later since the listing page has not been implemented now.

**Comment by anht-11** [comment]
1) Update the link to the website
2) you might consider removing step 1 in Test 1, as this user story only test the feature of viewing product detail page
3) remove test 2, as the feature of search bar is not implemented yet

**Comment by anht-11** [comment]
We might want to move this issue back to in progress, while we are working on establishing connection to database from the landing page endpoint.

**Comment by anht-11** [comment]
Update the acceptance tests accordingly with the specific test cases for different products shown in the landing page

**Comment by anht-11** [comment]
As we had a demo for this feature during our meeting, make sure to move it along the pipeline when you host the page the server and verify tests pass.
