### ISSUE TITLE
Create a transaction schema in database

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#74]
**Task Tests**

*Test 1*
1) Go the MyPHPAdmin management page,url: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/tbl_create.php?server=1&db=cse442_2023_spring_team_j_db
2) Select "table"
3) Verify that there is a "Transaction" table
4) Verify that the table has the following columns: id, amount, from_user, to_user, datetime, orderID

**Comment by anht-11** [comment]
@fhuang566 highly recommend link this task to the user story related to check out process

**Comment by anht-11** [comment]
@fhuang566 should this task block a user story in backlog or should it block a related user story?

**Comment by anht-11** [comment]
As this task is reopened, make sure to update the task label, add more test cases, and move it to the correct pipeline
