### ISSUE TITLE
 As an online shopper, I want to fill in my personal information including shipping address and payment information during the checkout process so I can ensure that my order is delivered to the correct address and that my preferred payment method is used to complete the transaction.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#9]
**Acceptance Test:**

*Test 1*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Verify if you are redirected to the Payment Page which requires you to fill in your Shipping Address which includes Address, Full name, Phone number, City, State and Zip code.
9. Verify the Payment Page which requires you to fill in your Payment Information which includes Card number, Name on card and Expiration date. 

*Test 2*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Address' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Address is required.' printed out.

*Test 3*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Full Name' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Full Name is required.' printed out.
9. Input "123!!!" to the 'Full Name' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Full Name can only contain letters.' printed out.

*Test 4*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input "abc" to the 'Phone Number' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Phone Number can only contain numbers and must be 10 digits.' printed out.
9. Input "123456789" to the 'Phone Number' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Phone Number can only contain numbers and must be 10 digits.' printed out.

*Test 5*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'City' text box, click on 'Confirm Order' button, verify that RED ERROR message 'City is required.' printed out.
9. Input "123!!!" to the 'City' text box, click on 'Confirm Order' button, verify that RED ERROR message 'City can only contain letters.' printed out.

*Test 6*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'State' text box, click on 'Confirm Order' button, verify that RED ERROR message 'State is required.' printed out.
9. Input "123!!!" to the 'State' text box, click on 'Confirm Order' button, verify that RED ERROR message 'State can only contain letters.' printed out.

*Test 7*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Zip Code' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Zip Code is required.' printed out.
9. Input "abc" to the 'Zip Code' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Zip Code can only contain numbers and must be 5 digits.' printed out.
10. Input "1234" to the 'Zip Code' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Zip Code can only contain numbers and must be 5 digits.' printed out.

*Test 8*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Card Number' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Card Number is required.' printed out.
9. Input "abc" to the 'Card Number' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Card Number can only contain numbers and must be 16 digits.' printed out.
10. Input "123456789" to the 'Card Number' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Card Number can only contain numbers and must be 16 digits.' printed out.

*Test 9*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Name on Card' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Name on Card is required.' printed out.
9. Input "123!!!" to the 'Name on Card' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Name on Card can only contain letters.' printed out.

*Test 10*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input nothing to the 'Expiration Date' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Expiration Date is required.' printed out.
9. Input "202303" to the 'Expiration Date' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Expiration Date must be in format 'YYYY/MM' and must be valid.' printed out.
10. Input "2023/13" to the 'Expiration Date' text box, click on 'Confirm Order' button, verify that RED ERROR message 'Expiration Date must be in format 'YYYY/MM' and must be valid.' printed out.

*Test 11*
1. Open the e-commerce website login page https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php.
2. Login with username "yixiao" and password "123456789" and click on 'Log in' button.
3. Click on 'Search' button on the top of screen.
4. Click on the image of the 'Handmade Mug'.
5. Click on "Add to Cart" button on the item page.
6. Click the button in the shape of a shopping cart in the upper right corner.
7. On the shopping cart page, click on the "Check Out" button.
8. Input "University at Buffalo" to the 'Address' text box.
9. Input "CSE" to the 'Full Name' text box.
10. Input "1234567890" to the 'Phone Number' text box.
11. Input "Buffalo" to the 'City' text box.
12. Input "New York" to the 'State' text box.
13. Input "14261" to the 'Zip Code' text box.
14. Input "1234123412341234" to the 'Card Number' text box.
15. Input "CSE" to the 'Name on Card' text box.
16. Input "2023/03" to the 'Expiration Date' text box.
17. Click on 'Confirm Order' button, verify if you are directed to confirmation page which shows order complete messages "Thank you for your order!", shipping address "University at Bufalo, Buffalo, New York, 14261" and total amount "$24.4".
18. Click the button in the shape of a shopping cart in the upper right corner and verify the cart is empty.

**Comment by anht-11** [comment]
As there are other information needs filled in the payment page, should we update the user story to better describe the functionality this user story support?

**Comment by anht-11** [comment]
I believe test 1 and test 2 can be grouped as one test, as they both share a happy test case, when user input all valid information. You might consider provide dummy data for personal information for the tester (the PM) as well.

You might consider the test case when user provide invalid inputs. In your test, be detailed what the user is expected to see when they provide invalid input. Think about what the error message should show and the behavior of the form.

**Comment by anht-11** [comment]
the page should be hosted on the server, so the link should goes to server, not the github repo

**Comment by anht-11** [comment]
Update test 1 with the link to the web site

**Comment by anht-11** [comment]
It seems the link to the website is the landing page, not login, so you might consider opt out the part login

**Comment by anht-11** [comment]
How would we plan to carry this issue to next sprint, given that we have designed a transaction schema? what kinds of query do we need? how would the payment page front-end interact with the database? Please leave the comment in the issue regarding your plan

**Comment by yigiaom** [comment]
Here is our plan to carry this user story to next sprint: 
To complete a transaction, we requires user to input their information in the payment page. Once they have valid inputs and click on the "Confirm Order" button, address, full name, phone number, city, state, zipcode should be stored in the database. Then user will be redirected to confirmation page which fetches the order number, amount and address information stored in database and shows on screen.

**Comment by anht-11** [comment]
What's happening behind the scene when clicking on the "confirm order" to redirect users to confirmation page?

**Comment by yigiaom** [comment]
Storing address, full name, phone number, city, state, zipcode and its corresponding order number, amount in a query.
Fetching these information from the query and displaying on the screen.
