### ISSUE TITLE
Use API to Get and Remove Data for Shopping Cart Page

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#90]
**Task Tests**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php, enter "user1" as the username and "12345678" as the password, then click on "Log In" button
2) Click on the button which shows a shopping cart icon in the top-right corner
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/cart.php, and if there is at least one item on the page
4) Select one item and click on the "REMOVE" button which is at the right corner of the product block, then verify if the block has disappeared.
5) If there is no product left, verify if there is "Your cart is empty." on the page.
6) Refresh the page, then verify the selected item has been removed permanently
7) Go to https://github.com/cse442-at-ub/project_s23-one-belt-one-road/blob/main/cart.php
8) Verify if the line require_once 'apiFunctions.php'; is in the code for using API
9) Verify if the line $cart_result = getUserCart($user_id); is in the code for using the function in API

**Comment by anht-11** [comment]
which user story does this task block?

**Comment by harptin** [comment]
Add a step to mention the API reference.
