### ISSUE TITLE
As a college student, I want to be able to sort the products by price, so I can easily find the products that fit my budget.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#91]
**Acceptance Test:**

*Test 1*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input keyword "mug" in the search bar on the landing page and click on Search button.
3. You will be redirected to item-listing page and be able to see 2 products related to the keyword: "Handmade Mug" and "Natural Raw Clay Mug".
4. Under the search bar, click on the dropdown menu, select "Price (Low to High)" and click on “Sort” button.
5. Verify the mugs are listed in the sorted order (smallest first).

*Test 2*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input keyword "o" in the search bar on the landing page and click on Search button.
3. You will be redirected to item-listing page and be able to see 6 products related to the keyword: "SPAM 12OZ", "Just Potatoes", "Burrito Bowl", "Hoodie In Beige", "Polar Fleece Set" and "Sun Screen Lotion".
4. Under the search bar, click on the dropdown menu, select "Price (Low to High)" and click on “Sort” button.
5. Verify the items are listed in the sorted order (smallest first).

*Test 3*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input keyword "mug" in the search bar on the landing page and click on Search button.
3. You will be redirected to item-listing page and be able to see 2 products related to the keyword: "Handmade Mug" and "Natural Raw Clay Mug".
4. Under the search bar, click on the dropdown menu, select "Price (High to Low)" and click on “Sort” button.
5. Verify the mugs are listed in the inversed order (largest first).

*Test 4*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input nothing in the search bar on the landing page and click on Search button directly.
3. You will be redirected to item-listing page and be able to see all 9 products on sale.
4. Under the search bar, click on the dropdown menu, select "Price (High to Low)" and click on “Sort” button.
5. Verify the items are listed in the inversed order (largest first).

*Test 5*
1. Open the e-commerce website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/.
2. Input keyword ' "" '(double quote) in the search bar on the landing page and click on Search button.
3. You will be redirected to item-listing page and be able to see no products matches the keyword.
4. Under the search bar, click on the dropdown menu, select "Price (Low to High)" and click on “Sort” button.
5. Verify nothing related to "" shows up.

**Comment by yigiaom** [comment]
Include the dropdown menu (be specific where is it and what does it looks like).

**Comment by anht-11** [comment]
How about a test case of searching key word "" and then sort by price?
