### ISSUE TITLE
As a buyer, I want to access my past orders so that I can keep track of my purchase history

### ISSUE THREAD

**Issue by harptin** [cse442-at-ub/project_s23-one-belt-one-road#99]
**Acceptance Tests**

*Test 1:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "user1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Purchase Orders" in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/purchase_orders.php
6) Verify if you can see existing orders, which contain information including the order number, the order datetime, items in the order with corresponding quantity, and the total amount.

*Test 2:*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/login.php
2) Enter the username "empty1" and the password "12345678", then click on "Log In"
3) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/account.php
4) Click on "Purchase Orders" in the center of the page
5) Verify if it is directed to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442j/purchase_orders.php
6) Verify if you can see "No past orders found" printed on the page

**Comment by anht-11** [comment]
split into two user stories for seller and buyer

**Comment by anht-11** [comment]
can we specify what to verify the existing orders (eg: order number, amount, quantity)?

**Comment by anht-11** [comment]
I would suggest remove the parenthesis part near the test number, as this part does not follow the Style Guide format
